services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: npx ng serve --host 0.0.0.0



